source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '9.0'

target 'MJCalendar_Example' do
  pod "MJCalendar", :path => "../"
  pod 'HexColors', '~> 2.3'
end

target 'MJCalendar_Tests' do
    pod "MJCalendar", :path => "../"

    pod 'Quick'
    pod 'Nimble'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'
        end
    end
end
